/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dictionary.E_VFile;
import Dictionary.SearchforJTextFiled;
import Dictionary.KhoTudien;
import Dictionary.V_EFile;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Collections;
import Dictionary.Sound;
import java.awt.Color;
import javax.swing.JMenuBar;
import javax.swing.event.AncestorEvent;
import Dictionary.Process;
import Dictionary.googleTranslate;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
/**
 *
 * @author ID
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setLocation(540, 130);
    }
    protected int select = 0;

    Process pr = new Process();

    //Các cửa sổ để chỉnh sửa
    AddJframe fADD = new AddJframe();
    EditJframe fEdit = new EditJframe();
    RemoveJframe fRemove = new RemoveJframe();
    GoogleTranslate fTranslate = new GoogleTranslate();
    //
    SearchforJTextFiled s = new SearchforJTextFiled();

    //Đọc tệp 
    E_VFile dic1 = new E_VFile();
    V_EFile dic2 = new V_EFile();

    //Voice
    Sound speak = new Sound();

    //Undo
    Stack<String> back = new Stack<>();
    Stack<String> up = new Stack<>();

    public void setupJlist() {
        if (select == 0) {
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < dic1.getKeys1().size(); i++) {
                model.addElement(dic1.getKeys1().get(i));
            }
            jList1.setModel(model);
        } else if (select == 1) {
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < dic2.getKeys2().size(); i++) {
                model.addElement(dic2.getKeys2().get(i));
            }
            jList1.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        E_V = new javax.swing.JButton();
        V_E = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        Sound = new javax.swing.JButton();
        translate = new javax.swing.JButton();
        Author = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SearchWord = new javax.swing.JTextField();
        Searcher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Back = new javax.swing.JButton();
        Up = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        E_V.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/English.png"))); // NOI18N
        E_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_VActionPerformed(evt);
            }
        });

        V_E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-vietnam-64.png"))); // NOI18N
        V_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_EActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-literature-100.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(E_V, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(V_E, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(V_E, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_V, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(116, 185, 255));

        add.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 18)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-new-64.png"))); // NOI18N
        add.setText("Add    ");
        add.setToolTipText("Add a word");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.setHideActionText(true);
        add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 2, 18)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-64.png"))); // NOI18N
        edit.setText("Edit    ");
        edit.setToolTipText("Edit a word");
        edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 18)); // NOI18N
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-64.png"))); // NOI18N
        remove.setText("Remove    ");
        remove.setToolTipText("Remove a word");
        remove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        Sound.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 18)); // NOI18N
        Sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/speak.png"))); // NOI18N
        Sound.setText(" Speak    ");
        Sound.setToolTipText("Speech a word you selected");
        Sound.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundActionPerformed(evt);
            }
        });

        translate.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 2, 18)); // NOI18N
        translate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-google-translate-64.png"))); // NOI18N
        translate.setText("Translate    ");
        translate.setToolTipText("Translate a paragraph");
        translate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateActionPerformed(evt);
            }
        });

        Author.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        Author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Author.setText("Create by Dinh Hiep and Mai Dat");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sound, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(translate)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Sound, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(translate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SearchWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchWordActionPerformed(evt);
            }
        });
        SearchWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchWordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchWordKeyReleased(evt);
            }
        });

        Searcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-64.png"))); // NOI18N
        Searcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearcherActionPerformed(evt);
            }
        });

        jList1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-back-32.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-forward-32.png"))); // NOI18N
        Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpMouseClicked(evt);
            }
        });
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Up, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchWord, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Searcher, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Searcher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SearchWord)
                        .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        fADD.setVisible(true);
        fADD.setLocation(getX() + 180, getY() + 150);
        fADD.jTextField1.setText("");
        fADD.jTextPane1.setText("");
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if (jList1.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Choose a word to edit!!");
        } else {
            fEdit.setVisible(true);
            fEdit.setLocation(getX() + 200, getY() + 150);
            fEdit.jTextField1.setText(jList1.getSelectedValue());
            fEdit.jTextPane1.setContentType("text/html");
            if (select == 0) {
                fEdit.jTextPane1.setText(dic1.getWord1().get(jList1.getSelectedValue()));
            } else {
                fEdit.jTextPane1.setText(dic2.getWord2().get(jList1.getSelectedValue()));
            }
        }
    }//GEN-LAST:event_editActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        if (jList1.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Choose a word to remove!!");
        } else {
            fRemove.setVisible(true);
            fRemove.setLocation(getX() + 200, getY() + 150);
            fRemove.jTextField1.setText(jList1.getSelectedValue());
        }
    }//GEN-LAST:event_removeActionPerformed

    private void SoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundActionPerformed
        if (jList1.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Choose a word!!");
        } else {
            speak.speak(jList1.getSelectedValue());
        }
    }//GEN-LAST:event_SoundActionPerformed

    private void SearcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearcherActionPerformed
        jTextPane1.setContentType("text/html");
        if (SearchWord.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Word is empty. Press!!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (select == 0) {
            if (dic1.getKeys1().contains(SearchWord.getText())) {
                back.peek();
                jTextPane1.setText(dic1.getWord1().get(SearchWord.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "The word was not found or no exist in dictionary!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (select == 1) {
            if (dic2.getKeys2().contains(SearchWord.getText())) {
                back.peek();
                jTextPane1.setText(dic2.getWord2().get(SearchWord.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "The word was not found or no exist in dictionary!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_SearcherActionPerformed

    private void E_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_VActionPerformed
        select = 0;
        setupJlist();
        SearchWord.setText("");
        jTextPane1.setText("");
    }//GEN-LAST:event_E_VActionPerformed

    private void V_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_EActionPerformed
        select = 1;
        setupJlist();
        SearchWord.setText("");
        jTextPane1.setText("");
    }//GEN-LAST:event_V_EActionPerformed

    private void jList1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jList1AncestorAdded
        setupJlist();
    }//GEN-LAST:event_jList1AncestorAdded

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (select == 0) {
            jTextPane1.setContentType("text/html");
            String str = jList1.getSelectedValue();
            SearchWord.setText(str);
            jTextPane1.setText(dic1.getWord1().get(str));
            if(str == null)
                back.push(str);
        } else if (select == 1) {
            jTextPane1.setContentType("text/html");
            String str = jList1.getSelectedValue();
            SearchWord.setText(str);
            jTextPane1.setText(dic2.getWord2().get(str));
            if(str == null)
                back.push(str);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void SearchWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWordKeyReleased
        if (select == 0) {
            ArrayList l;
            DefaultListModel model1 = new DefaultListModel();
            if (SearchWord.getText().trim().isEmpty()) {
                l = new ArrayList(dic1.getKeys1());
            } else {
                l = s.searchKey(SearchWord.getText(), dic1.getKeys1());
            }
            for (int i = 0; i < l.size(); i++) {
                model1.addElement(l.get(i));
            }
            jList1.setModel(model1);
        } else if (select == 1) {
            ArrayList l;
            DefaultListModel model2 = new DefaultListModel();
            if (SearchWord.getText().trim().isEmpty()) {
                l = new ArrayList(dic2.getKeys2());
            } else {
                l = s.searchKey(SearchWord.getText(), dic2.getKeys2());
            }
            for (int i = 0; i < l.size(); i++) {
                model2.addElement(l.get(i));
            }
            jList1.setModel(model2);
        }
    }//GEN-LAST:event_SearchWordKeyReleased

    private void SearchWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextPane1.setContentType("text/html");
            if (SearchWord.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Word is empty. Press!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (select == 0) {
                if (dic1.getKeys1().contains(SearchWord.getText())) {
                    if(SearchWord.getText()!= null)
                        back.push(SearchWord.getText());
                    jTextPane1.setText(dic1.getWord1().get(SearchWord.getText()));
                } else {
                    JOptionPane.showMessageDialog(null, "The word was not found or no exist in dictionary!!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (select == 1) {
                if (dic2.getKeys2().contains(SearchWord.getText())) {
                    if(SearchWord.getText()!= null)
                        back.push(SearchWord.getText());
                    jTextPane1.setText(dic2.getWord2().get(SearchWord.getText()));
                } else {
                    JOptionPane.showMessageDialog(null, "The word was not found or no exist in dictionary!!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_SearchWordKeyPressed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       
    }//GEN-LAST:event_BackActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        
    }//GEN-LAST:event_UpActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int a =  JOptionPane.showConfirmDialog(null, "Do you want to save all changes?", "Quit", JOptionPane.YES_NO_OPTION);
        if(a == JOptionPane.YES_OPTION){
            dic1.reloadFile();
            dic2.reloadFile();
        }   
    }//GEN-LAST:event_formWindowClosing

    private void translateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateActionPerformed
        fTranslate.setVisible(true);
        fTranslate.setLocation(getX() + 180, getY() + 150);
        fTranslate.jTextArea1.setText("");
        fTranslate.jTextPane1.setText("");
    }//GEN-LAST:event_translateActionPerformed

    private void SearchWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchWordActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        if(back.isEmpty()){
            return;
        }
        else{
            SearchWord.setText(back.peek());
            up.push(back.peek());
            back.pop();
            if(dic1.getWord1().containsKey(SearchWord.getText())){
                jTextPane1.setText(dic1.getWord1().get(SearchWord.getText()));
            }
            else if(dic2.getWord2().containsKey(SearchWord.getText())){
                jTextPane1.setText(dic2.getWord2().get(SearchWord.getText()));
            }
        }
    }//GEN-LAST:event_BackMouseClicked

    private void UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpMouseClicked
        if(up.isEmpty()){
            return;
        }
        else{
            SearchWord.setText(up.peek()); 
            back.push(up.peek());
            up.pop();
            if(dic1.getWord1().containsKey(SearchWord.getText())){
                jTextPane1.setText(dic1.getWord1().get(SearchWord.getText()));
            }
            else if(dic2.getWord2().containsKey(SearchWord.getText())){
                jTextPane1.setText(dic2.getWord2().get(SearchWord.getText()));
            }
        }
    }//GEN-LAST:event_UpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    public class AddJframe extends javax.swing.JFrame {

        /**
         * Creates new form AddJframe
         */
        private int type;
        private boolean check;

        public AddJframe() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            buttonGroup1 = new javax.swing.ButtonGroup();
            jButton1 = new javax.swing.JButton();
            jTextField1 = new javax.swing.JTextField();
            jButton3 = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jButton2 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTextPane1 = new javax.swing.JTextPane();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Add");
            setBackground(new java.awt.Color(0, 51, 255));

            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jButton3.setText("Cancel");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("New Word");

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("New Meaning");

            jButton2.setText("English");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton4.setText("Vietnamese");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Choose:");

            jScrollPane2.setViewportView(jTextPane1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addGap(48, 48, 48)
                                                    .addComponent(jButton3))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(83, 83, 83)
                                                            .addComponent(jButton2)
                                                            .addGap(107, 107, 107)
                                                            .addComponent(jButton4))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                                            .addGap(39, 39, 39)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                                                    .addComponent(jScrollPane2)))))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(jButton4)
                                            .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(34, 34, 34)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(75, 75, 75)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jButton3))
                                    .addContainerGap(46, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            setVisible(false);

        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (jTextField1.getText().trim().isEmpty() || jTextPane1.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Word is empty. Press!!", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
            } else if (type == 0) {
                if (dic1.getKeys1().contains(jTextField1.getText())) {
                    JOptionPane.showMessageDialog(null, "The word is already!!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    int a = JOptionPane.showConfirmDialog(null, "Do you want to add?", "Question", JOptionPane.YES_NO_OPTION);
                    if (a == JOptionPane.YES_OPTION) {
                        pr.add(jTextField1.getText(), jTextPane1.getText(), dic1.getWord1(), dic1.getKeys1());
                        JOptionPane.showMessageDialog(null, "Done!", "Done", -1);
                        setVisible(false);
                        setupJlist();
                    }
                }
            } else if (type == 1) {
                if (dic2.getKeys2().contains(jTextField1.getText())) {
                    JOptionPane.showMessageDialog(null, "The word is already!!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    int a = JOptionPane.showConfirmDialog(null, "Do you want to add?", "Question", JOptionPane.YES_NO_OPTION);
                    if (a == JOptionPane.YES_OPTION) {
                        pr.add(jTextField1.getText(), jTextPane1.getText(), dic2.getWord2(), dic2.getKeys2());
                        JOptionPane.showMessageDialog(null, "Done!", "Done", -1);
                        setVisible(false);
                        setupJlist();
                    }
                }
            }
        }

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1.setText("");
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            type = 0;
            JOptionPane.showMessageDialog(null, "You selected to add English!!", "Done!!", -1);
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
            type = 1;
            JOptionPane.showMessageDialog(null, "You selected to add Vietnamese!!", "Done!!", -1);
        }

        // Variables declaration - do not modify                     
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextPane jTextPane1;
        // End of variables declaration                   
    }

    /**
     *
     *
     */
    //
    //
    //Cửa sổ để xóa từ
    //
    //
    public class RemoveJframe extends javax.swing.JFrame {

        /**
         * Creates new form RemoveJframe
         */
        public RemoveJframe() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jTextField1 = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Remove");

            jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
            jLabel1.setText("Từ cần xóa:");

            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Cancel");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(94, 94, 94)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(97, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton2)
                                    .addGap(38, 38, 38))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2))
                                    .addGap(43, 43, 43))
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (jTextField1.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Choose a word to remove!");
                return;
            }
            if (!dic1.getKeys1().contains(jTextField1.getText().trim().toLowerCase()) && !dic2.getKeys2().contains(jTextField1.getText().trim().toLowerCase())) {
                JOptionPane.showMessageDialog(null, "The word was not found!!");
            }
            if (dic1.getKeys1().contains(jTextField1.getText().trim().toLowerCase())) {
                int a = JOptionPane.showConfirmDialog(null, "Do you want to remove?", "Question", JOptionPane.YES_NO_OPTION);
                if (a == JOptionPane.OK_OPTION) {
                    pr.remove(jTextField1.getText(), dic1.getWord1(), dic1.getKeys1());
                    JOptionPane.showMessageDialog(null, "Done!");
                    setupJlist();
                    fRemove.setVisible(false);
                }
            } else if (dic2.getKeys2().contains(jTextField1.getText().trim().toLowerCase())) {
                int a = JOptionPane.showConfirmDialog(null, "Do you want to remove?", "Question", JOptionPane.YES_NO_OPTION);
                if (a == JOptionPane.OK_OPTION) {
                    pr.remove(jTextField1.getText(), dic2.getWord2(), dic2.getKeys2());
                    JOptionPane.showMessageDialog(null, "Done!");
                    setupJlist();
                    fRemove.setVisible(false);
                }
            }

        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            fRemove.setVisible(false);
            jTextField1.setText("");
        }

        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField jTextField1;
        // End of variables declaration                   
    }

    /**
     *
     */

    //Cửa số để định nghĩa lại từ
    public class EditJframe extends javax.swing.JFrame {

        /**
         * Creates new form EditJframe
         */
        private int type;

        public EditJframe() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jTextField1 = new javax.swing.JTextField();
            jButton3 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jToggleButton1 = new javax.swing.JToggleButton();
            jToggleButton2 = new javax.swing.JToggleButton();
            jLabel3 = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTextPane1 = new javax.swing.JTextPane();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Edit");

            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Apply");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setText("Cancel");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Meaning");

            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Word");

            jToggleButton1.setText("Vietnamese");
            jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton1ActionPerformed(evt);
                }
            });

            jToggleButton2.setText("English");
            jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton2ActionPerformed(evt);
                }
            });

            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Choose:");

            jScrollPane2.setViewportView(jTextPane1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(jButton2)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(jButton3)
                                                    .addGap(53, 53, 53))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGap(13, 13, 13)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(39, 39, 39)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                            .addGap(50, 50, 50)
                                                                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                                                            .addComponent(jToggleButton1)
                                                                            .addGap(51, 51, 51))
                                                                    .addGroup(layout.createSequentialGroup()
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                                                                            .addGap(0, 0, Short.MAX_VALUE)))))))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jToggleButton1)
                                            .addComponent(jToggleButton2)
                                            .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1))
                                    .addContainerGap(66, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        y
        

        private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            type = 0;
            JOptionPane.showMessageDialog(null, "You selected to edit English!!", "Done!!", -1);
        }

        private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            type = 1;
            JOptionPane.showMessageDialog(null, "You selected to edit Vietnamese!!", "Done!!", -1);
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (dic1.getKeys1().contains(jList1.getSelectedValue())) {
                pr.modify(jList1.getSelectedValue(), jTextField1.getText(), jTextPane1.getText(), dic1.getWord1(), dic1.getKeys1());
                setupJlist();
            } else if (dic2.getKeys2().contains(jList1.getSelectedValue())) {
                pr.modify(jList1.getSelectedValue(), jTextField1.getText(), jTextPane1.getText(), dic2.getWord2(), dic2.getKeys2());
                setupJlist();
            }
            setVisible(false);
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            if (dic1.getKeys1().contains(jList1.getSelectedValue())) {
                pr.modify(jList1.getSelectedValue(), jTextField1.getText(), jTextPane1.getText(), dic1.getWord1(), dic1.getKeys1());
                JOptionPane.showMessageDialog(null, "Done!!");
                setupJlist();
            } else if (dic2.getKeys2().contains(jList1.getSelectedValue())) {
                pr.modify(jList1.getSelectedValue(), jTextField1.getText(), jTextPane1.getText(), dic2.getWord2(), dic2.getKeys2());
                JOptionPane.showMessageDialog(null, "Done!!");
                setupJlist();
            }

        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            fEdit.setVisible(false);
        }

        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextPane jTextPane1;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JToggleButton jToggleButton2;
        // End of variables declaration                   
    }
    
    public class GoogleTranslate extends javax.swing.JFrame {

    /**
     * Creates new form GoogleTranslate
     */
    //Tạo đối tượng để chạy API
    googleTranslate tran2  = new googleTranslate();
    public GoogleTranslate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Translate");

        jPanel3.setBackground(new java.awt.Color(255, 173, 106));
        jPanel3.setForeground(new java.awt.Color(255, 173, 106));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-sort-40.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                try {
                    jTextPane1KeyPressed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPane1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-speaker-filled-25.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton4ActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JavaLayerException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("English");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-right-50.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton2ActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(22, 22, 22)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-speaker-filled-25.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton5ActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JavaLayerException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vietnamese");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextPane1KeyReleased(java.awt.event.KeyEvent evt) {                                       
                
    }                                      

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                         
        String sub = null;
        sub = tran2.textTranslate(jLabel1.getText(), jLabel2.getText(), jTextPane1.getText());
        jTextArea1.setText(sub);
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String tmp="";
        tmp = jLabel1.getText();
        jLabel1.setText(jLabel2.getText());
        jLabel2.setText(tmp);
        tmp = jTextArea1.getText();
        jTextArea1.setText(jTextPane1.getText());
        jTextPane1.setText(tmp);
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, JavaLayerException {                                         
        tran2.speech(jTextPane1.getText(), jLabel1.getText());
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, JavaLayerException {                                         
        tran2.speech(jTextArea1.getText(), jLabel2.getText());
    }                                        

    private void jTextPane1KeyPressed(java.awt.event.KeyEvent evt) throws IOException {                                      
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String sub = null;
            sub = tran2.textTranslate(jLabel1.getText(), jLabel2.getText(), jTextPane1.getText());
            jTextArea1.setText(sub);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    
    public void Translate(){
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration                   

    private void showError(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JButton Back;
    private javax.swing.JButton E_V;
    private javax.swing.JTextField SearchWord;
    private javax.swing.JButton Searcher;
    private javax.swing.JButton Sound;
    private javax.swing.JButton Up;
    private javax.swing.JButton V_E;
    private javax.swing.JButton add;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton remove;
    private javax.swing.JButton translate;
    // End of variables declaration//GEN-END:variables
}
